In [118]:
import numpy as np

****Array Operations****

**Arithmetic Operations**

Performs Operations on corresponding elements of array 
Size of arrays must be same

In [119]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [120]:
#Sum
a1 + a2

array([ 7,  9, 11, 13, 15])

In [121]:
#Difference
a1 - a2

array([-5, -5, -5, -5, -5])

In [122]:
#Product
a1 * a2

array([ 6, 14, 24, 36, 50])

In [123]:
#Division
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [124]:
#Floor Division
a1 // a2

array([0, 0, 0, 0, 0])

In [125]:
#Power
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

**Broadcasting**

In [126]:
l=[1,2,3,4,5]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5])

In [127]:
arr+10

array([11, 12, 13, 14, 15])

In [128]:
arr2=np.arange(1,16).reshape(5,3)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [129]:
arr2+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22],
       [23, 24, 25]])

Broadcasting

In [130]:
l=[10,20,30,40]
arr=np.array(l)
arr

array([10, 20, 30, 40])

In [131]:
arr + 10

array([20, 30, 40, 50])

In [132]:
arr2=np.arange(1,21).reshape(4,5)

In [133]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [134]:
arr2=arr2*10

In [135]:
arr2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

**Deep and Shallow Copy**  
*Shallow Copy: When a arry is sliced  and performed operations in it sliced copy, no changes will occur in the original array as both are in seperate location in RAM*  
*Deep Copy: When a array is sliced and performed operations in it, the original array also changes as both variables are in the same location of RAM*

In [136]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [137]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [138]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [139]:
a[4:6] *10 

array([50, 60])

In [140]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b = a.copy() #Shallow Copy
# b=a     #Deep Copy
b[0] = 99 

In [142]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [143]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Matrix Operation**  

**Matrix Multiplication**  
*In Matrix, * is used for multiplication with boradcasting. But for actual matrix multiplication @ is used.*  
*Matrix1* @ *Matrix2*     *OR* np.dot(*Matrix1,Matrix2*) 

In [146]:
m=np.array([[1,2],[4,5]])
n=np.array([[7,8],[3,6]])

In [150]:
print("m:",m,"\nn:",n)

m: [[1 2]
 [4 5]] 
n: [[7 8]
 [3 6]]


In [ ]:
m * n #Broadcasting

array([[ 7, 16],
       [12, 30]])

In [ ]:
m @ n #Matrix Multiplication

array([[13, 20],
       [43, 62]])

**Transpose**  
*Rows and columns are replaced*  
*Matrix*.T

In [153]:
m.T

array([[1, 4],
       [2, 5]])