In [30]:
import numpy as np

**Indexing and Slicing of Vectors**

In [31]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Indexing

In [32]:
#Indexing works just like lists (starts from 0)
arr[2]

np.int64(13)

Slicing

In [33]:
#name[start:end] (start - include, end - exclude)
arr[:3] #if startign value is not given the default is 0 and if end is not given array is sliced till last element

array([11, 12, 13])

In [34]:
arr[:] #whole array is returend if not start or end index are given

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Steps is Slicing

In [35]:
#name[start::steps]
arr[3::2]


array([14, 16, 18, 20])

**Indexing and Slicing of Matrix**

In [36]:
a=np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Indexing

In [37]:
# name[row,column]
a[5,2]

np.int64(28)

Slicing

In [ ]:
#THe sliced portion is returend in vector if only one dimension is given
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [39]:
#If only one index is given then that will target rows
a[1]

array([ 6,  7,  8,  9, 10])

In [40]:
#For a portion, slice rows as well as columns
a[:2,2:4]

array([[3, 4],
       [8, 9]])

In [41]:
a[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [42]:
# Slicing a entire column
a[:,2]

array([ 3,  8, 13, 18, 23, 28])