In [1]:
import numpy as np

****Array Operations****

**Arithmetic Operations**

Performs Operations on corresponding elements of array 
Size of arrays must be same

In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [3]:
#Sum
a1 + a2

array([ 7,  9, 11, 13, 15])

In [4]:
#Difference
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
#Product
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
#Division
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
#Floor Division
a1 // a2

array([0, 0, 0, 0, 0])

In [8]:
#Power
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

**Broadcasting**

In [9]:
l=[1,2,3,4,5]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5])

In [10]:
arr+10

array([11, 12, 13, 14, 15])

In [11]:
arr2=np.arange(1,16).reshape(5,3)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [12]:
arr2+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22],
       [23, 24, 25]])