Importing Numpy

In [ ]:
import numpy as np

Creating a Numpy Array

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])

Array Function

In [ ]:
#1. Creating a array within a range with evenly spaced values
a=np.arange(2,22,2) #(start,stop,step)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#2. array of zeros (rows,columns)
b=np.zeros((3,3))
print(b)
#3. array of ones(rows,columns)
o=np.ones((2,2))
o

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1.],
       [1., 1.]])

In [ ]:
#4. Array of evenly spaced numbers over a specified interval
p=np.linspace(1,50,10) # (start,end,number_of_elements)
p

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])