Importing Numpy

In [2]:
import numpy as np

Creating a Numpy Array

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9])

Array Function

In [4]:
#1. Creating a array within a range with evenly spaced values
a=np.arange(2,22,2) #(start,stop,step)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
#2. array of zeros (rows,columns)
b=np.zeros((3,3))
print(b)
#3. array of ones(rows,columns)
o=np.ones((2,2))
o

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1.],
       [1., 1.]])

In [6]:
#4. Array of evenly spaced numbers over a specified interval
p=np.linspace(1,50,10) # (start,end,number_of_elements)
p

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

Random Array Generation (using Random Library)

In [7]:
#1. Random Array
#   Normalization (0 - 1)
np.random.rand(10)

array([0.55038768, 0.40894246, 0.46307043, 0.78044853, 0.72093919,
       0.60286377, 0.76378697, 0.72996619, 0.05453395, 0.32036831])

In [8]:
#   Standardization (-3 - 3)
np.random.randn(10)

array([ 0.55125856, -0.68648572, -1.02940009, -2.44538629,  1.07706704,
        0.35214331,  0.11140976,  0.03315298,  0.03893998,  0.95937565])

In [10]:
#2. Random numbers within specific range   
np.random.randint(10,20,4) #(start,end,size)

array([14, 14, 16, 13], dtype=int32)

Array Attributes

In [11]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#1. Returns number of rows and columns of array
arr.shape

(3, 3)

In [13]:
#2. Returns number of elements
arr.size

9

In [14]:
#3. Returns datatype
arr.dtype

dtype('int64')